language: generic
sudo: false
os: linux

env:
  matrix:
    - PYTHON=3.6 NUMPY=1.12.1 PANDAS=0.20.1 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=

matrix:
  fast_finish: true
  include:
  - os: osx
    env: PYTHON=3.6 NUMPY=1.12.1 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=
  # Together with fast_finish, allow build to be marked successful before the OS X job finishes
  allow_failures:
  - os: osx
    # This needs to be the exact same line as above
    env: PYTHON=3.6 NUMPY=1.12.1 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=

install: source continuous_integration/travis/install.sh
script:
  - source continuous_integration/travis/run_tests.sh
  - flake8 dask
  - if [[ $TEST_IMPORTS == 'true' ]]; then source continuous_integration/travis/test_imports.sh; fi
after_success: source continuous_integration/travis/after_success.sh

notifications:
  email: false
