language: generic
sudo: false
os: linux

env:
  matrix:
    - PYTHON=2.7 NUMPY=1.11.3 PANDAS=0.19.0 COVERAGE='true' PARALLEL='false' TEST_IMPORTS='false' XTRATESTARGS=
    - PYTHON=2.7 NUMPY=1.12.1 PANDAS=0.20.1 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='false' PYTHONOPTIMIZE=2 XTRATESTARGS=--ignore=dask/diagnostics
    - PYTHON=3.4 NUMPY=1.10.4 PANDAS=0.19.1 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='false' PYTHONOPTIMIZE=2 XTRATESTARGS=--ignore=dask/diagnostics
    - PYTHON=3.5 NUMPY=1.11.3 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='false' XTRATESTARGS=
    - PYTHON=3.6 NUMPY=1.12.1 PANDAS=0.20.1 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=

matrix:
  fast_finish: true
  include:
  - os: osx
    env: PYTHON=3.6 NUMPY=1.12.1 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=
  # Together with fast_finish, allow build to be marked successful before the OS X job finishes
  allow_failures:
  - os: osx
    # This needs to be the exact same line as above
    env: PYTHON=3.6 NUMPY=1.12.1 PANDAS=0.19.2 COVERAGE='false' PARALLEL='true' TEST_IMPORTS='true' XTRATESTARGS=

install: source continuous_integration/travis/install.sh
script:
  - source continuous_integration/travis/run_tests.sh
  - flake8 dask
  - if [[ $TEST_IMPORTS == 'true' ]]; then source continuous_integration/travis/test_imports.sh; fi
after_success: source continuous_integration/travis/after_success.sh

notifications:
  email: false
